"""add inventory lifecycle

Revision ID: aa12d2df8f01
Revises: 656b400b42d2
Create Date: 2026-03-14 11:22:09.841916

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aa12d2df8f01"
down_revision: str | None = "656b400b42d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("alert_type", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("severity", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("message", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
        sa.Column("entity_type", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("is_acknowledged", sa.Boolean(), nullable=False),
        sa.Column(
            "acknowledged_by",
            sqlmodel.sql.sqltypes.AutoString(length=200),
            nullable=True,
        ),
        sa.Column("acknowledged_at", sa.DateTime(), nullable=True),
        sa.Column("is_resolved", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alerts_alert_type"), "alerts", ["alert_type"], unique=False)
    op.create_index(op.f("ix_alerts_severity"), "alerts", ["severity"], unique=False)
    op.create_table(
        "consumption_log",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("inventory_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("quantity_used", sa.Float(), nullable=False),
        sa.Column("quantity_remaining", sa.Float(), nullable=False),
        sa.Column("consumed_by", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("purpose", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
        sa.ForeignKeyConstraint(
            ["inventory_id"],
            ["inventory.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_consumption_log_inventory_id"),
        "consumption_log",
        ["inventory_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consumption_log_product_id"),
        "consumption_log",
        ["product_id"],
        unique=False,
    )
    op.add_column("products", sa.Column("min_stock_level", sa.Float(), nullable=True))
    op.add_column("products", sa.Column("max_stock_level", sa.Float(), nullable=True))
    op.add_column("products", sa.Column("reorder_quantity", sa.Float(), nullable=True))
    op.add_column("products", sa.Column("shelf_life_days", sa.Integer(), nullable=True))
    op.add_column(
        "products",
        sa.Column(
            "storage_requirements",
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=True,
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "is_hazardous",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "is_controlled",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "is_controlled")
    op.drop_column("products", "is_hazardous")
    op.drop_column("products", "storage_requirements")
    op.drop_column("products", "shelf_life_days")
    op.drop_column("products", "reorder_quantity")
    op.drop_column("products", "max_stock_level")
    op.drop_column("products", "min_stock_level")
    op.drop_index(op.f("ix_consumption_log_product_id"), table_name="consumption_log")
    op.drop_index(op.f("ix_consumption_log_inventory_id"), table_name="consumption_log")
    op.drop_table("consumption_log")
    op.drop_index(op.f("ix_alerts_severity"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_alert_type"), table_name="alerts")
    op.drop_table("alerts")
    # ### end Alembic commands ###
