"""add usage_events table

Revision ID: c2aac49e8a9f
Revises: 4ecede3a6f58
Create Date: 2026-03-19 17:51:59.845452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2aac49e8a9f'
down_revision: Union[str, None] = '4ecede3a6f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_events',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('page', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_events_event_type'), 'usage_events', ['event_type'], unique=False)
    op.create_index('ix_usage_events_type_timestamp', 'usage_events', ['event_type', 'timestamp'], unique=False)
    op.create_index('ix_usage_events_user_timestamp', 'usage_events', ['user_email', 'timestamp'], unique=False)
    op.create_index('ix_alert_entity', 'alerts', ['entity_type', 'entity_id'], unique=False)
    op.alter_column('inventory', 'quantity_on_hand',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               nullable=True)
    op.alter_column('order_items', 'quantity',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               nullable=True)
    op.create_index(op.f('ix_orders_order_date'), 'orders', ['order_date'], unique=False)
    op.alter_column('products', 'storage_temp',
               existing_type=sa.VARCHAR(length=500),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=True)
    op.alter_column('products', 'extra',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('vendors', 'aliases',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendors', 'aliases',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('products', 'extra',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('products', 'storage_temp',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_index(op.f('ix_orders_order_date'), table_name='orders')
    op.alter_column('order_items', 'quantity',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               nullable=False)
    op.alter_column('inventory', 'quantity_on_hand',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               nullable=False)
    op.drop_index('ix_alert_entity', table_name='alerts')
    op.drop_index('ix_usage_events_user_timestamp', table_name='usage_events')
    op.drop_index('ix_usage_events_type_timestamp', table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_event_type'), table_name='usage_events')
    op.drop_table('usage_events')
    # ### end Alembic commands ###
